Repository DeebotUniverse/Deebot-4-Home-Assistant, pull requests merged in 2021-11, with the labels that each got.

#12 rename live map
  custom_components/deebot/camera.py
Labels: pr: Breaking Change

#14 use python 3.8 plus features
  .pre-commit-config.yaml
Labels: pr: refactor

#13 group rooms together
  custom_components/deebot/vacuum.py
Labels: pr: Breaking Change

#15 add last_cleaning sensor + refactor entities
  README.md
  custom_components/deebot/binary_sensor.py
  custom_components/deebot/camera.py
  custom_components/deebot/entity.py
  custom_components/deebot/helpers.py
  custom_components/deebot/manifest.json
  custom_components/deebot/number.py
  custom_components/deebot/select.py
  custom_components/deebot/sensor.py
  custom_components/deebot/vacuum.py
  requirements.txt
Labels: pr: Breaking Change

#17 add event "deebot_cleaning_job"
  README.md
  custom_components/deebot/__init__.py
  custom_components/deebot/config_flow.py
  custom_components/deebot/const.py
  custom_components/deebot/helpers.py
  custom_components/deebot/manifest.json
  custom_components/deebot/util.py
  custom_components/deebot/vacuum.py
  requirements.txt
Labels: pr: new-feature

#20 disable sensors by default
  custom_components/deebot/sensor.py
Labels: pr: bugfix

#22 fix lgtm alerts
  README.md
  custom_components/deebot/entity.py
  custom_components/deebot/hub.py
Labels: pr: bugfix

#23 update pylint config
  pylintrc
Labels: pr: enhancement

#24 add entity categories and state classes
  custom_components/deebot/binary_sensor.py
  custom_components/deebot/number.py
  custom_components/deebot/select.py
  custom_components/deebot/sensor.py
Labels: enhancement

#25 entity categories require 2021.11
  custom_components/deebot/const.py
  hacs.json
Labels: pr: bugfix

#27 update to 0.0.1b6
  custom_components/deebot/binary_sensor.py
  custom_components/deebot/camera.py
  custom_components/deebot/const.py
  custom_components/deebot/manifest.json
  custom_components/deebot/number.py
  custom_components/deebot/select.py
  custom_components/deebot/sensor.py
  custom_components/deebot/vacuum.py
  requirements.txt
Labels: pr: dependency-update

#31 update deebot-client to 0.1.0
  custom_components/deebot/manifest.json
  requirements.txt
Labels: pr: dependency-update

#32 fix trace map bug
  custom_components/deebot/manifest.json
  requirements.txt
Labels: pr: bugfix

#37 Fix last_cleaning sensor
  custom_components/deebot/sensor.py
Labels: pr: bugfix

#39 Create ru.json
  custom_components/deebot/translations/ru.json
Labels: pr: new-feature

#41 Update russian translation
  custom_components/deebot/translations/ru.json
Labels: pr: enhancement

#34 Add switches for advanced mode, continuous cleaning and carpet auto fan speed boost
  custom_components/deebot/__init__.py
  custom_components/deebot/entity.py
  custom_components/deebot/manifest.json
  custom_components/deebot/number.py
  custom_components/deebot/select.py
  custom_components/deebot/sensor.py
  custom_components/deebot/switch.py
  custom_components/deebot/vacuum.py
  requirements.txt
Labels: pr: new-feature

#52 add remaining attribute for life span sensors
  custom_components/deebot/manifest.json
  custom_components/deebot/sensor.py
  requirements.txt
Labels: pr: new-feature

#56 convert enum correctly to json
  custom_components/deebot/util.py
Labels: pr: bugfix
